name: "dbt_hightouch"
version: "1.0.0"
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  dbt_hightouch:
    +schema: hightouch_audit
    intermediate:
      +materialized: ephemeral
